---
name: ci-casper-db-utils

on:
  push:
    branches:
      - "dev"
      - "feat-*"
      - "release-*"

  pull_request:
    branches:
      - "dev"
      - "feat-*"
      - "release-*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Audit
        uses: actions-rs/cargo@v1
        with:
          command: audit
          args: --deny warnings --deny warnings --ignore RUSTSEC-2022-0001 --ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2021-0139 --ignore RUSTSEC-2022-0061 --ignore RUSTSEC-2021-0145 --ignore RUSTSEC-2022-0041 --ignore RUSTSEC-2020-0168 --ignore RUSTSEC-2022-0092 --ignore RUSTSEC-2023-0044 --ignore RUSTSEC-2023-0045 --ignore RUSTSEC-2024-0370 --ignore RUSTSEC-2024-0375 --ignore RUSTSEC-2024-0384 --ignore RUSTSEC-2025-0004 --ignore RUSTSEC-2022-0093 --ignore RUSTSEC-2024-0344

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
